<template>
  <div class="wrapper" ref="wrapper">
    <ul class="content">
      <li>1</li>
      <li>2</li>
      <li>1</li>
      <li>2</li><li>1</li>
      <li>2</li>
      <li>1</li>
      <li>2</li><li>1</li>
      <li>2</li>
      <li>1</li>
      <li>2</li><li>1</li>
      <li>2</li>
      <li>1</li>
      <li>2</li><li>1</li>
      <li>1</li>
      <li>2</li><li>1</li>
      <li>2</li>
      <li>1</li>
      <li>100</li><li>100</li><li>100</li><li>100</li>
      <li>100</li><li>100</li><li>100</li><li>100</li>
      <li>100</li><li>100</li><li>100</li><li>100</li><li>100</li><li>100</li><li>100</li><li>100</li><li>100</li>
      <li>100</li><li>100</li><li>100</li><li>100</li><li>100</li><li>100</li><li>100</li><li>100</li>
      <li>1</li>
      <li>2</li><li>1</li>
      <li>2</li>
      <li>1</li>
      <li>2</li><li>1</li>
      <li>2</li>
      <li>1</li>
      <li>2</li><li>1</li>
      <li>2</li>
      <li>1</li>
      <li>2</li><li>1</li>
      <li>2</li>
      <li>1</li>
      <li>2</li><li>1</li>
      <li>2</li>
      <li>1</li>
      <li>2</li><li>1</li>
      <li>2</li>
      <li>1</li>
      <li>2</li><li>1</li>
      <li>2</li>
      <li>1</li>
      <li>2</li><li>1</li>
      <li>2</li>
      <li>1</li>
      <li>2</li><li>1</li>
      <li>2</li>
      <li>1</li>
      <li>2</li><li>1</li>
      <li>2</li>
      <li>1</li>
      <li>2</li><li>1</li>
      <li>2</li>
      <li>1</li>
      <li>2</li><li>1</li>
      <li>2</li>
      <li>1</li>
      <li>2</li><li>1</li>
      <li>2</li>
      <li>1</li>
      <li>2</li><li>1</li>
      <li>2</li>
      <li>1</li>
      <li>2</li><li>1</li>
      <li>2</li>
      <li>1</li>
      <li>2</li><li>1</li>
      <li>2</li>
      <li>1</li>
      <li>2</li><li>1</li>
      <li>2</li>
      <li>1</li>
      <li>2</li><li>1</li>
      <li>2</li>
      <li>1</li>
      <li>2</li><li>1</li>
      <li>2</li>
      <li>1</li>
      <li>2</li><li>1</li>
      <li>2</li>
      <li>1</li>
      <li>2</li><li>1</li>
      <li>2</li>
      <li>1</li>
      <li>2</li><li>1</li>
      <li>2</li>
      <li>1</li>
      <li>2</li><li>1</li>
      <li>2</li>
      <li>1</li>
      <li>2</li><li>1</li>
      <li>2</li>
      <li>1</li>
      <li>2</li><li>1</li>
      <li>2</li>
      <li>1</li>
      <li>2</li><li>1</li>
      <li>2</li>
      <li>1</li>
      <li>2</li><li>1</li>
      <li>2</li>
      <li>1</li>
      <li>2</li><li>1</li>
      <li>2</li>
      <li>1</li>
      <li>2</li><li>1</li>
      <li>2</li>
      <li>1</li>
      <li>2</li><li>1</li>
      <li>2</li>
      <li>1</li>
      <li>2</li><li>1</li>
      <li>2</li>
      <li>1</li>
      <li>2</li><li>1</li>
      <li>2</li>
      <li>1</li>
      <li>2</li><li>1</li>
      <li>2</li>
      <li>1</li>
      <li>2</li><li>1</li>
      <li>2</li>
      <li>1</li>
      <li>2</li><li>1</li>
      <li>2</li>
      <li>1</li>
      <li>2</li>
      <li>1</li>
      <li>2</li>
      <li>1</li>
      <li>2</li><li>1</li>
      <li>2</li>
      <li>1</li>
      <li>2</li><li>1</li>
      <li>2</li>
      <li>1</li>
      <li>2</li><li>1</li>
      <li>2</li>
      <li>1</li>
      <li>2</li><li>1</li>
      <li>2</li>
      <li>1</li>
      <li>2</li><li>1</li>
      <li>2</li>
      <li>1</li>
      <li>2</li><li>1</li>
      <li>2</li>
      <li>1</li>
      <li>2</li><li>1</li>
      <li>2</li>
      <li>1</li>
      <li>2</li><li>1</li>
      <li>2</li>
      <li>1</li>
      <li>2</li><li>1</li>
      <li>2</li>
      <li>1</li>
      <li>2</li><li>1</li>
      <li>2</li>
      <li>1</li>
      <li>2</li><li>1</li>
      <li>2</li>
      <li>1</li>
      <li>2</li><li>1</li>
      <li>2</li>
      <li>1</li>
      <li>2</li><li>1</li>
      <li>2</li>
      <li>1</li>
      <li>2</li><li>1</li>
      <li>2</li>
      <li>1</li>
      <li>2</li><li>1</li>
      <li>2</li>
      <li>1</li>
      <li>2</li><li>1</li>
      <li>2</li>
      <li>1</li>
      <li>2</li><li>1</li>
      <li>2</li>
      <li>1</li>
      <li>2</li><li>1</li>
      <li>2</li>
      <li>1</li>
      <li>2</li><li>1</li>
      <li>2</li>
      <li>1</li>
      <li>2</li><li>1</li>
      <li>2</li>
      <li>1</li>
      <li>2</li><li>1</li>
      <li>2</li>
      <li>1</li>
      <li>2</li><li>1</li>
      <li>2</li>
      <li>1</li>
      <li>2</li><li>1</li>
      <li>2</li>
      <li>1</li>
      <li>2</li><li>1</li>
      <li>2</li>
      <li>1</li>
      <li>2</li><li>1</li>
      <li>2</li>
      <li>1</li>
      <li>100</li><li>100</li><li>100</li><li>100</li>
      <li>100</li><li>100</li><li>100</li><li>100</li>
      <li>100</li><li>100</li><li>100</li><li>100</li><li>100</li><li>100</li><li>100</li><li>100</li><li>100</li>
      <li>100</li><li>100</li><li>100</li><li>100</li><li>100</li><li>100</li><li>100</li><li>100</li>
      <li>2</li><li>1</li>
      <li>2</li>
      <li>1</li>
      <li>2</li><li>1</li>
      <li>2</li>
      <li>1</li>
      <li>2</li><li>1</li>
      <li>2</li>
      <li>1</li>
      <li>2</li><li>1</li>
      <li>2</li>
      <li>1</li>
      <li>2</li><li>1</li>
      <li>2</li>
      <li>1</li>
      <li>2</li><li>1</li>
      <li>2</li>
      <li>1</li>
      <li>2</li><li>1</li>
      <li>2</li>
      <li>1</li>
      <li>2</li><li>1</li>
      <li>2</li>
      <li>1</li>
      <li>2</li><li>1</li>
      <li>2</li>
      <li>1</li>
      <li>2</li><li>1</li>
      <li>2</li>
      <li>1</li>
      <li>2</li><li>1</li>
      <li>2</li>
      <li>1</li>
      <li>2</li><li>1</li>
      <li>2</li>
      <li>1</li>
      <li>2</li><li>1</li>
      <li>2</li>
      <li>1</li>
      <li>2</li><li>1</li>
      <li>2</li>
      <li>1</li>
      <li>2</li><li>1</li>
      <li>2</li>
      <li>1</li>
      <li>2</li><li>1</li>
      <li>2</li>
      <li>1</li>
      <li>2</li><li>1</li>
      <li>2</li>
      <li>1</li>
      <li>2</li><li>1</li>
      <li>2</li>
      <li>1</li>
      <li>2</li><li>1</li>
      <li>2</li>
      <li>1</li>
      <li>2</li><li>1</li>
      <li>2</li>
      <li>1</li>
      <li>2</li>
    </ul>
  </div>
  </template>

  <script>
      import BScroll from 'better-scroll'

      export default {
          name: "VueTest",
          mounted() {
              // let wrapper = document.querySelector('.wrapper')
              // console.log(wrapper)
              // this.scroll = new BScroll(this.$refs.wrapper, {})
              // this.$nextTick(() => {
              //     this.scroll = new BScroll(this.$refs.wrapper, {})
              // })
              let wrapper = this.$refs.wrapper
              var that_ = this
              setTimeout(function(){
                  that_.scroll = new BScroll(wrapper, {})
              },20)
          }
      }
  </script>

  <style lang='stylus' scoped>
      @import "~styles/varibles.styl"
  </style>
